### CONSTANTES
@baseUrl = http://victor.controllab.com:8000/api/v1


### Listar Agendamentos
GET {{baseUrl}}/schedule
Authorization: Bearer {{token}}


### Criar Agendamentos
PUT {{baseUrl}}/schedule
Authorization: Bearer {{token}}

{
  "version_form_id": 1,
  "periodicity_id": 1,
  "active": true,
  "method_id": 1,
  "year":2025
}

### Listar periodicidades
GET {{baseUrl}}/schedule/periodicity
Authorization: Bearer {{token}}
