### CONSTANTES
@baseUrl = http://victor.controllab.com:8000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IiIsImV4cCI6MTczNjQzMTU4NCwiaWQiOjEsInVzdWFyaW8iOiJ2aWN0b3IifQ.BHS3awHTDlOwW_vKCSzaUumEHPNzOCYwb5YAeZzBuIM


### TODOS OS FORMULÁRIOS
GET {{baseUrl}}/form
Content-Type: application/json
Authorization: Bearer {{token}}


### CRIAR UM FORMULÁRIO
PUT {{baseUrl}}/formulario
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Teste",
    "descricao": "Descrição do teste",
    "ativo": true
}

### DELETAR 1 FORMULARIO
DELETE {{baseUrl}}/formulario/1
Content-Type: application/json
Authorization: Bearer {{token}}

### ATIVAR/DESATIVAR 1 FORMULARIO
PATCH {{baseUrl}}/formulario
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 2,
    "descricao": ""
}



### formularios

[
    {
        "id": 1,
        "nome": "Epidemiológicos",
        "descricao": "descricao",
    },
     {
        "id": 2,
        "nome": "Teste",
        "descricao": "descricao",
    }
]

### Agendamentos

[
    {
    "id": "int",
    "id_formulario": "int",
    "versao_formulario": "int",
    "user": "string",
    "periodicidade": "string",
    "inicio": "date",
    "unificado": "bool",
    "ativo": "bool"
    },
]