
@baseUrl = http://victor.controllab.com:8000/api/v1


POST {{baseUrl}}/user/login
Content-Type: application/json
Origin: http://rafaeld-gse.controllab.com:3000/
X-Forwarded-For: 101.124.54

{
    "username": "victor",
    "password": "victor"
}
> {%
    client.global.set("token", response.body.token);
%}

### list
GET {{baseUrl}}/user
Authorization: Bearer {{token}}
Content-Type: application/json
# Origin: http://rafaeld-gse.controllab.com:3000/



### create user 
PUT {{baseUrl}}/user/create

{
    "user": "bp",
    "password": "bp",
    "email": "bp@email.com",
    "name": "bp",
    "enterprise_id": 1
}

### list
GET {{baseUrl}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

### add group 
POST {{baseUrl}}/user/grupamento
Authorization: Bearer {{token}}

{
   "user_id": [5],
   "grupamento_id":1
}


### del group
DELETE  {{baseUrl}}/user/grupamento
Authorization: Bearer {{token}}

{
   "user_id": 5,
   "grupamento_id":1
}

