### CONSTANTES
@baseUrl = http://victor.controllab.com:8000/api/v1


### tipos
GET {{baseUrl}}/variaveis/tipo
Authorization: Bearer {{token}}

### grupamento
GET {{baseUrl}}/variaveis/grupamento
Authorization: Bearer {{token}}

### criar grupamento
PUT {{baseUrl}}/variaveis/grupamento
Authorization: Bearer {{token}}

{
    "nome": "Exame"
}

### variaveis
GET {{baseUrl}}/variaveis
Authorization: Bearer {{token}}


### variaveis
PUT {{baseUrl}}/variaveis
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "grupamento_id": 6,
  "obrigatorio": true,
  "possui_item": false,
  "texto": "Pergunta1",
  "tipo_variavel_id": 2
}


### Grupamento
GET  {{baseUrl}}/grupamento
Content-Type: application/json
Authorization: Bearer {{token}}


### responder
POST  {{baseUrl}}/answer
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "variable_id": 12,
  "schedule_id": 1,
  "value":0,
  "active": true
}

### saber respostas
GET  {{baseUrl}}/answer?schedule_id=1
Content-Type: application/json
Authorization: Bearer {{token}}

